#!/usr/bin/env python3
from __future__ import annotations
import pathlib
import argparse
import os
import typing
import json
import pprint
import dataclasses
import tarfile

attr_getter_t = typing.TypeVar('attr_getter_t')

class attr_getter(typing.Generic[attr_getter_t]):

    def __getattribute__(self, name: str) -> typing.Any:

        value = super().__getattribute__(name)
        if name.startswith('_'):
            return value

        or_use = getattr(self, '_or_use', ...)
        if or_use is not ...:
            delattr(self, '_or_use')

        if value is not ...:
            return value
        if or_use is not ...:
            return or_use

        raise ValueError(f"Cannot read {self.__class__.__name__}().{name} when it is not initialized.")

    def or_use(self, value: typing.Any) -> attr_getter_t:
        if value is ...:
            raise ValueError('value=...')
        setattr(self, '_or_use', value)
        return typing.cast(attr_getter_t, self)

@dataclasses.dataclass
class asset_info_impl:
    id: typing.Any = ...
    label: typing.Any = ...
    browser_download_url: str = typing.cast(str, ...)
    uploader: typing.Any = ...
    name: str = typing.cast(str, ...)
    digest: typing.Any = ...
    updated_at: typing.Any = ...
    node_id: typing.Any = ...
    download_count: typing.Any = ...
    created_at: typing.Any = ...
    content_type: typing.Any = ...
    state: typing.Any = ...
    url: typing.Any = ...
    size: typing.Any = ...

class asset_info(attr_getter[asset_info_impl], asset_info_impl):
    pass

@dataclasses.dataclass
class release_info_impl:
    assets: list[asset_info] = typing.cast(list[asset_info], ...)
    assets_url: typing.Any = ...
    author: typing.Any = ...
    body: typing.Any = ...
    created_at: typing.Any = ...
    draft: typing.Any = ...
    html_url: typing.Any = ...
    id: typing.Any = ...
    immutable: typing.Any = ...
    mentions_count: typing.Any = ...
    name: typing.Any = ...
    node_id: typing.Any = ...
    prerelease: typing.Any = ...
    published_at: typing.Any = ...
    reactions: typing.Any = ...
    tag_name: typing.Any = ...
    tarball_url: typing.Any = ...
    target_commitish: typing.Any = ...
    updated_at: typing.Any = ...
    upload_url: typing.Any = ...
    url: typing.Any = ...
    zipball_url: typing.Any = ...

class release_info(attr_getter[release_info_impl], release_info_impl):
    pass

@dataclasses.dataclass
class file_info:
    os: str
    arch: str
    url: str
